all: build

build:
	$(MAKE) -C ReactNative.Forms
	$(MAKE) -C ReactNative.Forms.Droid
	$(MAKE) -C ReactNative.Forms.iOS

clean:
	$(MAKE) clean -C ReactNative.Forms
	$(MAKE) clean -C ReactNative.Forms.Droid
	$(MAKE) clean -C ReactNative.Forms.iOS
